config/routes.rb
Rails.application.routes.draw do
    root to: 'toppages#index'
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'

    get 'signup', to: 'users#new'
    
    resources :users
    
    resources :schedules, only: [:index, :show, :new, :create, :edit, :update] do
        member do 
            put :reserve
            put :cancel 
        end
    end
    
    resource :password, only: [:show, :edit, :update]

    namespace :admin do 
        root "top#index"
        resources :schedules
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :schedules
    
    validates :number, :name, presence: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :room
  belongs_to :user, optional: true
  enum segment:[:'午前', :'午後'] 
  
  validates :date, :segment, :status, presence: true
  validates :date, uniqueness: { scope: [:segment, :room_id] }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    attr_accessor :current_password
    validates :password, presence: { if: :current_password }
    
    has_many :schedules
    
    has_secure_password
end

app/controllers/admin/base.rb
class Admin::Base < ApplicationController
  before_action :admin_login_required
  
  private 
  def admin_login_required
    redirect_to login_path unless current_user&.admin?
  end
end

    

app/controllers/admin/schedules_controller.rb
class Admin::SchedulesController < Admin::Base
    def new
        if Schedule.all
            @schedule = Schedule.last
        else
            @schedule = Schedule.new(day: Date.today)
        end
    end 
    
    def create
        start_day = Schedule.last.date + 1
        last_day = start_day.end_of_month

        (start_day..last_day).each do |day|
            Schedule.create(date: day, segment: 0,room_id: 1)
            Schedule.create(date: day, segment: 1,room_id: 1)
            Schedule.create(date: day, segment: 0,room_id: 2)
            Schedule.create(date: day, segment: 1,room_id: 2)
        end 
        flash[:success] = '新たな予約枠を設定しました。'
       redirect_to admin_root_path 
    end
end

app/controllers/admin/top_controller.rb
class Admin::TopController < Admin::Base
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    
    private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in
  
  def show
    redirect_to login_url
  end
  
  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    current_password = params[:user][:current_password]
    
    if current_password.present?
     if @user.authenticate(current_password)
       @user.assign_attributes(edit_user_params)
       if @user.save
         flash[:success] = 'パスワードを変更しました。'
         redirect_to @user
       else
         flash.now[:danger] = 'パスワードの変更に失敗しました。'
         render :edit
       end
      else
        flash.now[:danger] = '現在のパスワードが一致しません。'
        render :edit
     end
    end
  end
  
  private
  def edit_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :require_user_logged_in
  #before_action :check_user, only: [:show,:edit,:update,:destroy]
    
    def index
      @schedules = Schedule.order(id: :asc).page(params[:page]).per(25)
    end
    
    def show
      @schedule = Schedule.find(params[:id])  
    end
    
    def edit
      @schedule = Schedule.find(params[:id])
    end

    def update
      @schedule = Schedule.find(params[:id])
      @schedule.status = 1
      @schedule.user = current_user
      @schedule.update(schedule_params)
      redirect_to schedule_path(@schedule)
    end 
    
    def reserve
      schedule = Schedule.find(params[:id])
      #schedule.status = 1
      #schedule.user = current_user
      #schedule.save
      #redirect_back(fallback_location: root_url)
      #@schedule = schedule
      redirect_to edit_schedule_path(schedule)
    end
    
    def cancel
      schedule = Schedule.find(params[:id])
      schedule.status = 0
      schedule.user = nil
      schedule.title = nil
      schedule.description = nil
      schedule.save
      redirect_back(fallback_location: root_url)
    end
    
   
   private

   def schedule_params
      params.require(:schedule).permit(:date, :segment, :title, :description)
   end 
   
  def check_user
    #redirect_to signup_url if @task.nil? || current_user != @task.user
    redirect_to root_url if current_user != @schedule&.user
    return
  end
  
end

   

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  before_action :check_admin, only: [:new, :create]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
      @user = User.new(user_params)

      if @user.save
        flash[:success] = 'ユーザを登録しました。'
        redirect_to @user
      else
        flash.now[:danger] = 'ユーザの登録に失敗しました。'
        render :new
      end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def check_admin
    unless current_user&.admin?
      redirect_to login_url 
    end
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/admin/schedules/new.html.erb
<h1>新たな予約枠の設定</h1>

<p>設定済みの最終日:<%= @schedule.date %></p>


 <%= link_to '次の１ヶ月を設定する', admin_schedules_path, method: :post, class: 'btn btn-primary' %>

app/views/admin/top/index.html.erb
<div class='container'>
<h1>管理ページトップ</h1> 
  <ul class='list-unstyled'>
    <li><%= link_to 'User登録',signup_path, class: 'btn btn-primary mb-2' %></li>
    <li><%= link_to 'Users', users_path, class: 'btn btn-primary mb-2' %></li>
    <li><%= link_to 'schedule追加', new_admin_schedule_path , class: 'btn btn-primary' %></li>
  </ul>
</div>

 

app/views/layouts/_admin_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">MeetingManager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
       
          <li class="nav-item"><%= link_to '管理者top', :admin_root, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'USER登録', '#', class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        
        </ul>
      </div>
  </nav>
</header>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">MeetingManager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
       
       <% if current_user&.admin %>
          <li class="nav-item"><%= link_to 'User登録',signup_path, class: 'nav-link' %></li>
       　　<li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
       <% end %>
 
       
       <% if logged_in? %>
             <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
          
        <% else %>
           <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
           
        <% end %>
        
        </ul>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta neme='viewport' content='width=device-width,initial-scale=1,shrink-to-fit=no'>
    <title>MeetingManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
 
  </head>

  <body>
    <%=  if controller.kind_of?(Admin::Base)
            render 'layouts/admin_navbar'
          else
            render 'layouts/navbar'
          end %>
      
    <div  class='container'>
       <%= render "layouts/flash_messages" %>
       
        <%= yield %>
    </div>
  </body>
</html>

app/views/schedules/_schedules.htmi.erb
<ul class="list-unstyled">
  <p>日付、区分、会議室</p>
  <% @schedules.each do |schedule| %>
    <li>
      <%= schedule.date %>
      <%= schedule.segment %>
      <%= schedule.room.name %>
      <% if schedule.status == 0 %>
          <%= link_to '予約する', reserve_schedule_path(schedule), method: :put %>
      <% else %>
          <%= '予約済み' %>
      <% end %>
      
    </li>
  <% end %>
 
</ul>

app/views/schedules/edit.html.erb
  <p>会議の詳細を入力する</p>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @schedule, local: true) do |f| %>
     
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="row">
        <p>日付：</p><%= @schedule.date  %>
      </div>

      <div class="row">
        <P>区分：</P><%= @schedule.segment %>
      </div>

      <div class="row">
        <p>会議室：</p><%= @schedule.room.name %>
      </div>

      <div class="form-group">
        <%= f.label :title, '会議名' %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :description, '説明' %>
        <%= f.text_area :description, class: 'form-control',rows: 5  %>
      </div>

      <%= f.submit 'update', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/schedules/index.html.erb
<h1>会議室一覧</h1>

 <table class='table table-striped' >
  <thead class='thead-dark text-center'>
    <tr><th>日付</th><th>区分</th><th>会議室</th><th>予約状況</th></tr>
  </thead> 
  
  <% @schedules.each do |schedule| %>
    　<tr>
    　  <td><%= schedule.date %></td>
    　 <td><%= schedule.segment %></td>
       <td><%= schedule.room.name %></td>
       <td>
          <% if schedule.status == 0 %>
            <%= link_to '予約する', reserve_schedule_path(schedule), method: :put %>
          <% else %>
            <%= '予約済み' %>
          <% end %>
        </td>
      </tr>
  <% end %>
  
</table>

 <%= paginate @schedules %>
   
<%= link_to 'ユーザ詳細に戻る', user_path(current_user) %>
 

app/views/schedules/show.html.erb
 <p>会議室の予約状況</p>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

      <%= render 'layouts/error_messages', model: @schedule %>

      <div class="row">
        <p>日付：</p><%= @schedule.date  %>
      </div>

      <div class="row">
        <P>区分：</P><%= @schedule.segment %>
      </div>

      <div class="row">
        <P>区分：</P><%= @schedule.room.name %>
      </div>

      <div class="row">
        <p>会議の名前：</p><%= @schedule.title %>
      </div>
      
      <div class="row">
        <p>説明：</p><%= @schedule.description %>
      </div>
      
      <%= link_to  'ユーザー詳細に戻る', user_path(current_user) %>
      
  </div>
  
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>

   <%= link_to  'ユーザー詳細に戻る', user_path(current_user) %>
    
    
   
<% else %>

  <div class='center jumbotron'>
    <div class="text-center">
      <h1> Welcome to the MeetingManager</h1>
      <%= link_to 'Login!', login_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 80 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <% if user == current_user %>
                <p><%= link_to 'View profile', user_path(current_user) %></p>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

 
<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
     
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <div class="form-check">
        <%= f.check_box :admin, class: 'form-check-input' %>
        <%= f.label :admin, ' admin' %>
        
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-3">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= current_user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(current_user, { size: 250 }) %>" alt="">
      </div>
    </div>
    <div class='mb-1'>
    <%= link_to '新規予約する', schedules_path, class: 'btn btn-primary' %>
    </div>
    <%= link_to 'パスワードを変更する', edit_password_path, class: 'btn btn-primary' %>
    
 
  </aside>
  <div class="col-sm-9">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item">あなたが予約している会議室</li>
    </ul>
    
     <table clas='table'>
      <thead class='thead-dark text-center'>
        <tr><th>日付</th><th>区分</th><th>会議室</th><th>タイトル</th><tH>確認・取消</th></tr>
      </thead>
      <% schedules = Schedule.where(status: 1).where(user: current_user).order(id: :asc) %>
      <% schedules.each do |schedule| %>
      <tbody>
        <tr>
            <td><%= schedule.date %></td>
            <td><%= schedule.segment %></td>
            <td><%= schedule.room.name %></td>
            <td><%= schedule.title %></td>
          <td>
            <% if schedule.status == 1 %>
              <%= link_to '確認する', schedule_path(schedule) %>
              <%= link_to '取り消す', cancel_schedule_path(schedule), method: :put %>
            <% end %>
          </td>
         </tr>
      <% end %>
        
      </tbody>
    </table>
    
  </div>

</div>

    
      